/**
 * Offline cache. Generated by build.mjs - edit templates/sw.js, not sw.js.
 *
 * Why this exists: a guide is read standing outside with one bar of signal, and
 * that is exactly when a network fetch fails. Every page opened once stays
 * readable afterwards.
 *
 * Strategy:
 *   navigation requests  network first, fall back to cache, then to the index
 *   everything else      cache first, revalidate in the background
 *
 * The cache name carries the build stamp, so a deploy retires the old cache
 * instead of serving yesterday's guide to a phone that never reloaded.
 */

const CACHE = "flater-{{VERSION}}";
const PRECACHE = {{PRECACHE}};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting())
      // A failed precache must not block install - the page still works online.
      .catch(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;

  if (request.method !== "GET" || new URL(request.url).origin !== self.location.origin) {
    return;
  }

  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
          return response;
        })
        .catch(() => caches.match(request).then((hit) => hit || caches.match("/")))
    );
    return;
  }

  event.respondWith(
    caches.match(request).then((hit) => {
      const network = fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
          return response;
        })
        .catch(() => hit);
      return hit || network;
    })
  );
});
